version: "3"
services:
  pgdev:
    container_name: aptabase_pgdev
    restart: always
    image: postgres:15
    volumes:
      - pgdev-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: aptabase_pw

  clickhousedev:
    container_name: aptabase_clickhousedev
    image: clickhouse/clickhouse-server:23.8.4.69
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - clickhousedev-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: aptabase
      CLICKHOUSE_PASSWORD: aptabase_pw
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  mailcatcher:
    container_name: aptabase_mailcatcher
    image: dockage/mailcatcher:0.8.2
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  pgdev-data:
    driver: local
  clickhousedev-data:
    driver: local